### ISSUE TITLE
Прохождение авторизации

### ISSUE THREAD

**Issue by amr-dallin** [umidjons/paycom-integration-php-template#1]
Здравствуйте, Умид. Для получения доступа к апи, мне не удаётся пройти базовую авторизацию.

В качестве данных аутентификации я привожу:
login: Paycom (как в примере)
password: key (получен из Paycom Merchants).

Response:
`{
"error":{"message":"Access deniet.", "code":-32504, "data": "invalid_authorization_header"},
"jsonrpc":"2.0"
}`

В платформе тестирования все запросы завершаются с ошибкой -32504

Спасибо.

**Comment by umidjons** [comment]
Здравствуйте.
Попробуйте через curl или postman достучаться до endpoint указанный в настройках веб кассы.
Что то подобное:
```
curl -vvv -X POST -H "Authorization: Basic UGF5Y29tOnlzRmZOJlNOQSNReSZZVEN5NldqolFEZXh1SFNQTXcjLnBnNx==" -H "Accept: application/json" -H "Content-Type: application/json" -d '{
    "jsonrpc": "2.0",
    "id": 110,
    "method": "CheckPerformTransaction",
    "params": {
        "amount": 50000,
        "account": {
            "order_id": 123
        }
    }
}' "http://yoursite.uz/paycom/api/"
```

**Comment by amr-dallin** [comment]
Здравствуйте.

Не совсем понимаю, почему вы предлагаете достучаться до endpoint?

Я обращаюсь на прямую к http://checkout.test.paycom.uz/api, формируя curl запрос со всеми необходимыми http заголовками (на PHP):

```
<?php
$login = 'Paycom';
$key = '******************************************'; //ключ получен из Paycom Merchants
$url = 'http://checkout.test.paycom.uz/api';

$data = [
    'jsonrpc' => '2.0',
    'id' => 234,
    'method' => 'CheckPerformTransaction',
    'params' => [
        'amount' => 50000,
        'account' => [
            'phone' => '935816051'
        ]
    ]
];
$data_string = json_encode($data);

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_TIMEOUT, 30);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'Authorization: Basic ' . base64_encode($login . ':' . $key),
        'Accept: application/json',
        'Content-Type: application/json; charset=utf-8'
    ]
);
curl_setopt($ch, CURLINFO_HEADER_OUT, true);
curl_setopt($ch, CURLOPT_HEADER, true);

$result = curl_exec($ch);

print_r(curl_getinfo($ch, CURLINFO_HEADER_OUT));
print_r($result);

curl_close($ch);
```

В итоге, получаю следующий результат:
```
POST /api HTTP/1.1
Host: checkout.test.paycom.uz
Authorization: Basic UGF5Y29tOkNYWU80ZXQwbiVIJjVEREIyemJKdERUNkhiN3d4WUsjP2pXRg==
Accept: application/json
Content-Type: application/json; charset=utf-8
Content-Length: 119

HTTP/1.1 200 OK
Server: nginx/1.10.1
Date: Tue, 28 Feb 2017 18:00:01 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 106
Connection: keep-alive
Server-Time: 1488304801789
Response-Time: 0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST, GET
Access-Control-Allow-Headers: Content-Type, X-Auth
Access-Control-Expose-Headers: Content-Type

{"error":{"message":"Access deniet.","code":-32504,"data":"invalid_authorization_header"},"jsonrpc":"2.0"}
```

Еще такой вопрос. В каких случаях используется merchant_id(в файле paycom.config.sample.php)? Просмотрел всё api и не нашел его применение. Не нужно ли его использовать для авторизации? Почему используется, в качестве login, значение "Paycom"?

**Comment by umidjons** [comment]
Оплата инициируется по веб форме по `POST` запросу на `http://checkout.test.paycom.uz`, клиент перенаправляется на нашу страницу оплаты, где он вносить свои данные (номер карты + срок или авторизуется в нашей платформе по телефону), после этого пейком отправляет серию запросов (`CheckPerformTransaction`, `CreateTransaction`...) на указанный вами `Endpoint URL` в настройках веб кассы. Endpoint URL это путь где расположена реализация API, этот API авторизует пейкома, поэтому логин всегда Paycom.

**Comment by amr-dallin** [comment]
Теперь разобрался и все работает. Спасибо, Умид, за разъяснение.
